name: build proto files
on:
  push:
    branches:
      - master
    # paths:
    #   - "apis/proto/**"

jobs:
  build:
    name: build all
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: sudo apt-get update
      - run: sudo apt-get install -y libprotobuf-dev libprotoc-dev protobuf-compiler
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: mkdir -p $HOME/local
      - run: wget https://dl.google.com/go/go1.13.linux-amd64.tar.gz
      - run: tar xzvf go1.13.linux-amd64.tar.gz
      - run: mv go $HOME/local/go
      - run: GOPATH=$HOME/go PATH=$PATH:$HOME/local/go/bin make
