name: build proto files
on:
  push:
    branches:
      - master
    # paths:
    #   - "apis/proto/**"

jobs:
  build:
    name: build all
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libprotobuf-dev libprotoc-dev protobuf-compiler
      - run: make
